name: test
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
  schedule:
    - cron: "0 16 * * *"

concurrency:
  group: workflow-example-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.1-noble
      options: --ipc=host
    strategy:
      matrix:
        node-version: ["lts/jod"]
    steps:
      - uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Run tests
        run: pnpm test
