name: test
on:
  - push
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10.0, 21.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Install playwright
        run: npx playwright install --with-deps
      - name: Run tests
        run: npm test